config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"
  authenticate :user do
    resources :modes, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :vehicles, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :prices, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :deadlines, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/deadline.rb
class Deadline < ApplicationRecord
  belongs_to :mode
  validates :min_distance, :max_distance, :deadline, :mode_id, presence: true

end

app/models/mode.rb
class Mode < ApplicationRecord
  has_many :vehicles
  has_many :prices
  has_many :deadlines
  validates :name, :min_distance, :max_distance, :min_weight, :max_weight, :fixed_fee, presence: true
  validates :name, uniqueness: true
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :mode
  validates :min_weight, :max_weight, :price_per_km, :mode_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :mode

  validates :plate, :brand, :model, :category, :year, :capacity, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    modes_path
  end
end

app/controllers/deadlines_controller.rb
class DeadlinesController < ApplicationController
  before_action :set_deadline, only: %i[edit update destroy ]
  before_action :set_modes, only: %i[new create edit]
  # GET /deadlines or /deadlines.json
  def index
    @deadlines = Deadline.all
  end


  # GET /deadlines/new
  def new
    @deadline = Deadline.new
  end

  # GET /deadlines/1/edit
  def edit
  end

  # POST /deadlines or /deadlines.json
  def create
    @deadline = Deadline.new(deadline_params)
    if @deadline.save
      flash[:notice] = 'Deadline created successfully'
      return redirect_to deadlines_path
    end
    @modes = Mode.all.order(:name)
    flash.now[:alert] = 'Error creating deadline'
    render :new, status: :unprocessable_entity
  end

  # PATCH/PUT /deadlines/1 or /deadlines/1.json
  def update
    if @deadline.update(deadline_params)
      flash[:notice] = "Deadline updated successfully"
      return redirect_to deadlines_path
    end
    @modes = Mode.all.order(:name)
    flash.now[:alert] = "Error updating deadline"
    render :edit, status: :unprocessable_entity
  end

  def destroy
    if @deadline.destroy
      flash[:notice] = "Deadline deleted successfully"
      return redirect_to deadlines_path
    end
    flash.now[:alert] = "Error deleting deadline"
    render :index, status: :unprocessable_entity    
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deadline
      @deadline = Deadline.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def deadline_params
      params.require(:deadline).permit(:min_distance, :max_distance, :deadline, :mode_id)
    end

    def set_modes
      @modes = Mode.all.order(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/modes_controller.rb
class ModesController < ApplicationController
  before_action :mode_find, only: [:show, :edit, :update, :destroy]
  def index
    @modes = Mode.all
  end

  def show
    @prices = Price.where(mode_id: @mode.id).order(:min_weight)
    @deadlines = Deadline.where(mode_id: @mode.id).order(:min_distance)
    @in_operation = Vehicle.where(mode_id: @mode.id, status: true).order(:plate)
    @in_maintenance = Vehicle.where(mode_id: @mode.id, status: false).order(:plate)
  end

  def new
    @mode = Mode.new
  end

  def create
    @mode = Mode.new(mode_params)
    if @mode.save
      flash[:notice] = t("mode_created_successfully")
      return redirect_to modes_path
    end
    flash.now[:alert] = t("error_on_creating_mode")
    render :new, status: :unprocessable_entity
  end

  def edit

  end

  def update
    if @mode.update(mode_params)
      flash[:notice] = "Mode updated successfully"
      return redirect_to @mode
    end
    flash.now[:alert] = "Error on updating mode"
    render :edit, status: :unprocessable_entity
  end

  def destroy
    if @mode.destroy
      flash[:notice] = "Mode deleted successfully"
      return redirect_to modes_path
    end
    flash.now[:alert] = "Error on deleting mode"
    render :show, status: :unprocessable_entity
  end

  private

  def mode_params
    params.require(:mode).permit(:name, :min_distance, :max_distance, :min_weight, :max_weight, :fixed_fee, :active)
  end

  def mode_find
    @mode = Mode.find(params[:id])
  end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_modes, only: [:new, :create, :edit, :update]
  before_action :find_price, only: [:edit, :update, :destroy]
  def index
    @prices = Price.all
  end
  

  def new 
    @price = Price.new 
  end

  def create 
    @price = Price.new(price_params)
    if @price.save
      flash[:notice] = "Price successfully registered" 
      return redirect_to prices_path
    end
    flash.now[:alert] = "Error registering price"
    render :new, status: :unprocessable_entity
  end

  def destroy
    if @price.destroy
      flash[:notice] = "Price deleted successfully"
      return redirect_to prices_path
    end
    flash.now[:alert] = "Error deleting price"
    render :index, status: :unprocessable_entity
  end

  def edit
    
  end

  def update
    if @price.update(price_params)
      flash[:notice] = "Price updated successfully"
      return redirect_to prices_path
    end
    flash.now[:alert] = "Error updating price"
    render :edit, status: :unprocessable_entity
  end

  private

  def price_params
    params.require(:price).permit(:min_weight, :max_weight, :price_per_km, :mode_id)
  end

  def set_modes
    @modes = Mode.all.order(:name)
  end

  def find_price
    @price = Price.find(params[:id])
  end
  
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: %i[ show edit update destroy ]

  # GET /vehicles or /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1 or /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
    @modes = Mode.all.order(:name)
  end

  # GET /vehicles/1/edit
  def edit
    @modes = Mode.all.order(:name)
  end

  # POST /vehicles or /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      flash[:notice] = "Vehicle created successfully."
      return redirect_to vehicles_path
    end
    @modes = Mode.all.order(:name)
    flash.now[:alert] = 
"Error while creating the vehicle."
    render :new, status: :unprocessable_entity
  end

  # PATCH/PUT /vehicles/1 or /vehicles/1.json
  def update
    if @vehicle.update(vehicle_params)
      flash[:notice] = "Vehicle updated successfully"
      return redirect_to @vehicle
    end
    @modes = Mode.all.order(:name)
    flash.now[:alert] = "Error while updating the vehicle"
    render :edit, status: :unprocessable_entity
  end

  # DELETE /vehicles/1 or /vehicles/1.json
  def destroy
    if @vehicle.destroy
      flash[:notice] = "Vehicle deleted successfully"
      return redirect_to vehicles_path
    end
    flash.now[:alert] = "Error while deleting the vehicle"
    render :show, status: :unprocessable_entity
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_params
      params.require(:vehicle).permit(:mode_id, :plate, :brand, :model, :category, :year, :capacity, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deadlines_helper.rb
module DeadlinesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/modes_helper.rb
module ModesHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/deadlines/_deadline.html.erb
<div id="<%= dom_id deadline %>">
</div>

app/views/deadlines/_form.html.erb
<% if deadline.errors.any? %>
  <div class="messages alert alert-warning" role="alert">
    <p><%= t('verify_the_following_errors') %>:</p>
    <ul>
      <% deadline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form">
  <%= form_with(model: deadline) do |f| %>
    <table class="deadlines__form table table-success table-striped">
      <tr>
        <th><%= f.label :min_distance, t('min_distance') << ' (Km)', class: "form-label" %></th>
        <td><%= f.number_field :min_distance, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :max_distance, t('max_distance') << ' (Km)', class: "form-label" %></th>
        <td><%= f.number_field :max_distance, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :deadline, t('deadline') << ' (hrs)', class: "form-label" %></th>
        <td><%= f.number_field :deadline, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :mode_id, t('mode'), class: "form-label" %></th>
        <td><%= f.collection_select :mode_id, @modes, :id, :name, {}, { class: "form-select" } %></td>
      </tr>
    </table>
    <div class="deadlines__btn">
      <%= f.submit t('save'), class: "btn btn-success" %>
    </div>  
  <% end %>
</div>

app/views/deadlines/edit.html.erb
<section>
  <div class="deadlines">
    <h1><%= t('edit') << " " << t('deadline') %></h1>
    <%= button_to(t("back"), deadlines_path, method: :get, class: "btn btn-primary deadlines__btn") %>
    <%= render partial: "form", locals: { deadline: @deadline } %>
  </div>
</section>

app/views/deadlines/index.html.erb
<section>
  <div class="deadlines">
    <h1><%= t('deadlines') %></h1>
    <p><%= link_to t('new_deadline'), new_deadline_path, class: "btn btn-primary" %></p>
  </div>
  <div class="deadlines__list">
    <% if @deadlines.empty? %>
      <h3><%= t('no_deadlines_registered') %></h3>
    <% else %>
      <table class="deadlines__list container table table-success table-striped">
        <thead>
          <tr>
            <th scope="col" colspan="2"><%= t('distance') %></th>
            <th scope="col"><%= t('deadline') %></th>
            <th scope="col"><%= t('mode') %></th>
            <th scope="col" colspan="2"><%= t('actions') %></th>
          </tr>
        </thead>
        <tbody>
          <% @deadlines.each do |deadline| %>
            <tr>
              <td><%= deadline.min_distance %> Km</td>
              <td><%= deadline.max_distance %> Km</td>
              <td><%= deadline.deadline %> hrs</td>
              <td><%= deadline.mode.name %></td>
              <td><%= button_to(t("edit"), edit_deadline_path(deadline.id), class: "btn btn-warning deadlines__btn", method: :get) %></td>
              <td><%= button_to(t("delete"),
                deadline_path(deadline.id),
                form: { data: { turbo_confirm: "Are you sure you want to delete this deadline? " }},
                class: "btn btn-danger deadlines__btn",
                method: :delete) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</section>

app/views/deadlines/new.html.erb
<section>
  <div class="deadlines">
    <h1><%= t('new_deadline') %></h1>
    <%= button_to(t("back"), deadlines_path, method: :get, class: "btn btn-primary deadlines__btn") %>
    <%= render partial: "form", locals: { deadline: @deadline } %>
  </div>
</section>

app/views/deadlines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @deadline %>

<div>
  <%= link_to "Edit this deadline", edit_deadline_path(@deadline) %> |
  <%= link_to "Back to deadlines", deadlines_path %>

  <%= button_to "Destroy this deadline", @deadline, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LogisticsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body class=<%= user_signed_in? ? "d-flex flex-nowrap" : "" %>>
    <header class="bg-dark" data-bs-theme="dark">
      <div class="container">
        <% if user_signed_in? %>
          <%= render partial: "shared/user_header" %>
        <% else %>
          <%= render partial: "shared/visitor_header" %>
        <% end %>
      </div>
    </header>
    <main>
      <div class="container <%= user_signed_in? ? "main__login" : "" %>">
        <% flash.each do |type, msg| %>
          <div class="notice alert <%= flash[:alert] ? 'alert-danger' : 'alert-success' %>" role="alert">
            <%= msg %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </main>
    <footer></footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/da4ddd9139.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/modes/_form.html.erb
<div class="messages">
  <!-- Existe alguma mensagem de erro de sistema? -->
  <% if(mode.errors.any?) %>
     <div class="messages alert alert-warning alert-dismissible fade show" role="alert">
     <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <p><%= t('verify_the_following_errors') %>:</p>
      <ul>
        <% mode.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="form">
  <%= form_with(model: mode) do |f| %>
    <table class="modes__form table table-success table-striped">
      <tr>
        <th><%= f.label :name, class: "form-label" %></th>
        <td><%= f.text_field :name, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :min_distance, t('min_distance') << ' (Km)', class: "form-label" %></th>
        <td><%= f.number_field :min_distance, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :max_distance, t('max_distance') << ' (Km)', class: "form-label" %> </th>
        <td><%= f.number_field :max_distance, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :min_weight, t('min_weight') << ' (Kg)', class: "form-label" %></th>
        <td><%= f.number_field :min_weight, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :max_weight, t('max_weight') << ' (Kg)', class: "form-label" %></th>
        <td><%= f.number_field :max_weight, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :fixed_fee, t('fixed_fee') << ' ($)', class: "form-label" %></th>
        <td><%= f.number_field :fixed_fee, class: "form-control" %></td>
      </tr>
      <tr>
        <th><%= f.label :active, t('status'), class: "form-label" %></th>
        <td>
          <%= f.check_box :active, class: "form-check-input" %> 
        </td>
      </tr>
    </table>
    <div class="modes__btn">
      <%= f.submit t('save'), class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/modes/edit.html.erb
<section>

  <div class="modes">

    <h1><%= t('edit') << " " << t('mode') %></h1>

    <%= button_to(t("back"), modes_path, method: :get, class: "btn btn-primary modes__btn") %>

  </div>

  <div class="modes__list">

    <%= render partial: "form", locals: { mode: @mode } %>

  </div>

</section>

app/views/modes/index.html.erb
<section>
  <div class="modes">
    <h1><%= t('modes') %></h1>
    <p><%= link_to t('new_mode'), new_mode_path, class: "btn btn-primary" %></p>
  </div>
  <div class="modes__list">
    <% if @modes.empty? %>
      <h3><%= t('no_modes_registered') %></h3>
    <% else %>
      <table class="suppliers__list container table table-success table-striped">
        <thead>
          <tr>
            <th scope="col"><%= t('name') %></th>
            <th scope="col"><%= t('min_distance') %> (Km)</th>
            <th scope="col"><%= t('max_distance') %> (Km)</th>
            <th scope="col"><%= t('status') %></th>
          </tr>
        </thead>
        <tbody>
          <% @modes.each do |mode| %>
            <tr>
              <td scope="row"><%= link_to mode.name, mode_path(mode.id) %></td>
              <td><%= mode.min_distance %></td>
              <td><%= mode.max_distance %></td>
              <td>
                <span class="<%= mode.active ? 'active' : 'inactive' %>">
                  <%= mode.active ? t('active') : t('inactive') %>
                </span>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</section>

app/views/modes/new.html.erb
<section class="modes">
  <div class="modes__title">
    <h1><%= t('new_mode') %> </h1>
  </div>
  <div class="modes__list">
    <%= render partial: "form", locals: { mode: @mode } %>
  </div>
</section>

app/views/modes/show.html.erb
<section>
  <div class="modes">
    <h1><%= t('mode') %></h1>
    <%= button_to(t("back"), modes_path, method: :get, class: "btn btn-primary modes__btn") %>

    <table class="modes__table table table-success table-striped">
      <tr>
        <th><%= t('name') %></th>
        <td><%= @mode.name %></td>
      </tr>
      <tr>
        <th><%= t('min_distance') %></th>
        <td><%= @mode.min_distance %> Km</td>
      </tr>
      <tr>
        <th><%= t('max_distance') %></th>
        <td><%= @mode.max_distance %> Km</td>
      </tr>
      <tr>
        <th><%= t('min_weight') %></th>
        <td><%= @mode.min_weight %> Kg</td>
      </tr>
      <tr>
        <th><%= t('max_weight') %></th>
        <td><%= @mode.max_weight %> Kg</td>
      </tr>
      <tr>
        <th><%= t('fixed_fee') %></th>
        <td><%= t('$') %> <%= @mode.fixed_fee %></td>
      </tr>
      <tr>
        <th><%= t('status') %></th>
        <td>
          <span class="<%= @mode.active ? 'active' : 'inactive' %>">
            <%= @mode.active ? t('active') : t('inactive') %>
          </span>
        </td>
      </tr>
    </table>
  </div>
  <div class="modes__btn-bottom">
    <%= button_to(t("edit"), edit_mode_path(@mode.id), method: :get, class: "btn btn-warning") %>
    <%= button_to(t("delete"), mode_path(@mode.id), method: :delete, class: "btn btn-danger") %>
  </div>
  <div class="modes__price-list">
    <h3><%= t('pricing_table') %></h3>
    <% if @prices.empty? %>
      <h5><%= t('this_modal_does_not_has_pricing_table') %></h5>
    <% else %>
      <table class="container table table-success table-striped">
        <thead>
          <tr>
            <th scope="col" colspan="2"><%= t('weight') %></th>
            <th scope="col"><%= t('price_per_km') %></th>
          </tr>
        </thead>
        <tbody>
          <% @prices.each do |price| %>
            <tr>
              <td><%= price.min_weight %> Kg</td>
              <td><%= price.max_weight %> Kg</td>
              <td>$ <%= price.price_per_km %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
  <div class="modes__deadline-list">
    <h3><%= t('deadlines_table') %></h3>
    <% if @deadlines.empty? %>
      <h5><%= t('this_modal_does_not_has_deadlines_table') %></h5>
    <% else %>
      <table class="container table table-success table-striped">
        <thead>
          <tr>
            <th scope="col" colspan="2"><%= t('distance') %></th>
            <th scope="col"><%= t('deadline') %></th>
          </tr>
        </thead>
        <tbody>
          <% @deadlines.each do |deadline| %>
            <tr>
              <td><%= deadline.min_distance %> Kg</td>
              <td><%= deadline.max_distance %> Kg</td>
              <td>$ <%= deadline.deadline %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
  <div class="modes__in_operation-list">
    <h3><%= t('in_operation_vehicles') %></h3>
    <% if @in_operation.empty? %>
      <h5><%= t('this_modal_does_not_have_in_operation_vehicles') %></h5>
    <% else %>
      <table class="container table table-success table-striped">
        <thead>
          <tr>
            <th scope="col"><%= t('plate') %></th>
            <th scope="col"><%= t('model') %></th>
            <th scope="col"><%= t('category') %></th>
          </tr>
        </thead>
        <tbody>
          <% @in_operation.each do |vehicle| %>
            <tr>
              <td><%= vehicle.plate %></td>
              <td><%= vehicle.model %></td>
              <td><%= vehicle.category %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

  <div class="modes__in_maintenance-list">
    <h3><%= t('in_maintenance_vehicles') %></h3>
    <% if @in_maintenance.empty? %>
      <h5><%= t('this_modal_does_not_have_in_maintenance_vehicles') %></h5>
    <% else %>
      <table class="container table table-success table-striped">
        <thead>
          <tr>
            <th scope="col"><%= t('plate') %></th>
            <th scope="col"><%= t('model') %></th>
            <th scope="col"><%= t('category') %></th>
          </tr>
        </thead>
        <tbody>
          <% @in_maintenance.each do |vehicle| %>
            <tr>
              <td><%= vehicle.plate %></td>
              <td><%= vehicle.model %></td>
              <td><%= vehicle.category %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

</section>

app/views/prices/index.html.erb
<section>
  <div class="prices">
    <h1><%= t('prices') %></h1>
    <p><%= link_to t('new_price'), new_price_path, class: "btn btn-primary" %></p>
  </div>
  <div class="prices__list">
    <% if @prices.empty? %>
      <h3><%= t('no_prices_registered') %></h3>
    <% else %>
      <table class="suppliers__list container table table-success table-striped">
        <thead>
          <tr>
            <th scope="col" colspan="2"><%= t('weight') %></th>
            <th scope="col"><%= t('price_per_km') %></th>
            <th scope="col"><%= t('mode') %></th>
            <th scope="col" colspan="2"><%= t('actions') %></th>
          </tr>
        </thead>
        <tbody>
          <% @prices.each do |price| %>
            <tr>
              <td><%= price.min_weight %> Kg</td>
              <td><%= price.max_weight %> Kg</td>
              <td>$ <%= price.price_per_km %></td>
              <td><%= price.mode.name %></td>
                <td><%= button_to(t("edit"), edit_price_path(price.id), class: "btn btn-warning prices__btn", method: :get) %></td>
              <td><%= button_to(t("delete"),
                price_path(price.id),
                form: { data: { turbo_confirm: "Are you sure you want to delete this price?" }},
                class: "btn btn-danger prices__btn",
                method: :delete) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</section>

app/views/vehicles/index.html.erb
<section>
  <div class="vehicles">
    <h1><%= t('vehicles') %></h1>
    <p><%= link_to t('new_vehicle'), new_vehicle_path, class: "btn btn-primary" %></p>
  </div>
  <div class="modes__list">
    <% if @vehicles.empty? %>
      <h3><%= t('no_vehicles_registered') %></h3>
    <% else %>
      <table class="suppliers__list container table table-success table-striped">
        <thead>
          <tr>
            <th scope="col"><%= t('plate') %></th>
            <th scope="col"><%= t('model') %></th>
            <th scope="col"><%= t('category') %></th>
            <th scope="col"><%= t('status') %></th>
          </tr>
        </thead>
        <tbody>
          <% @vehicles.each do |vehicle| %>
            <tr>
              <td scope="row"><%= link_to vehicle.plate, vehicle_path(vehicle.id) %></td>
              <td><%= vehicle.model %></td>
              <td><%= vehicle.category %></td>
              <td>
                <span class="<%= vehicle.status ? 'active' : 'inactive' %>">
                  <%= vehicle.status ? t('in_operation') : t('in_maintenance') %>
                </span>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</section>

app/views/vehicles/show.html.erb
<section>
  <div class="vehicles">
    <h1><%= t('vehicle') %></h1>
    <%= button_to(t("back"), vehicles_path, method: :get, class: "btn btn-primary vehicles__btn") %>
    <table class="vehicle__table table table-success table-striped">
      <tr>
        <th><%= t('plate') %></th>
        <td><%= @vehicle.plate %></td>
      </tr>
      <tr>
        <th><%= t('brand') %></th>
        <td><%= @vehicle.brand %></td>
      </tr>
      <tr>
        <th><%= t('model') %></th>
        <td><%= @vehicle.model %></td>
      </tr>
      <tr>
        <th><%= t('category') %></th>
        <td><%= @vehicle.category %></td>
      </tr>
      <tr>
        <th><%= t('year') %></th>
        <td><%= @vehicle.year %></td>
      </tr>
      <tr>
        <th><%= t('capacity') %></th>
        <td><%= @vehicle.capacity %> Kg</td>
      </tr>
      <tr>
        <th><%= t('status') %></th>
        <td>
          <span class="<%= @vehicle.status ? 'active' : 'inactive' %>">
            <%= @vehicle.status ? t('in_operation') : t('in_maintenance') %>
          </span>
        </td>
      </tr>
    </table>
  </div>
 <div class="vehicles__btn-bottom">
    <%= button_to(t("edit"), edit_vehicle_path(@vehicle.id), method: :get, class: "btn btn-warning") %>
    <%= button_to(t("delete"), vehicle_path(@vehicle.id), method: :delete, class: "btn btn-danger", data: { turbo_method: :delete, "turbo-confirm": "Are you sure you want to delete this vehicle?" }) %>
  </div>
</section>